---
title: "hackathon_notes"
author: "Lee Richardson"
date: "02/24/2016"
output: html_document
---

# Notes on Reading 
Goals: Create novel + innovative applications which:  
  1. Increase the use in public health response and awareness
  2. Increase public health data access
  3. Increase understanding of complex public health systems 

- Small teams of developers will compete to create prototype mobile, web-based or stand-alone visualization applications

The application must be visualization focused.  This may include, but not limited to, techniques such as:
1. geographic spatial and temporal mapping
2. network graph visualizations
3. data information visualiz

The application should be interactive, allowing users to manipulate toggles and input to dynamically explore the data.

Judging criteria: 
1. Innovation:  How novel is your visualization application or approach? Does it present the public health data in new ways?

2. Quality: Does the application work as intended? Is the software easy to get up and running? How bug-free is the software? Given the short timeframe we do not expect well-polished software. Judging will be relative to other submissions

3. Usability: How easy is it to use the application? How easy does the application make navigating the data? Is the presentation intuitive and understandable by a wide audience?

4. Impact: What is the potential for this application to impact public health awareness, response, and practice?

# Project Tycho
This is a project to advance the availability and use of pubic health data. Namely, by collecting and integrating weekly data across a variety of sources. Put on mainly by the epidimiology deprtment at UPitt!

# Ideas-----------
- Distance vs. Correlation PLot 
- ggplot time series 
- Fitting a spline through the time series 
- Comparison's for the Time series (Multple Time Series)

- Uncertainty around the splines 
- Maps (Tomrrow)
- Histograms/Bar Charts 
- Add text explanations to describe what's going on


- STRETCH Kriging (value, covariance model, and a grid)
  - Fit a spatial model
  - Cut the time Range (Start overall)
  - Table viewer (raw data)
- STRETCH- Mouse over text 

- STRETCH- Movies (Tomorrow)
  - County level USA Map. 
  - Centroid's of each county 
  - Interpolate the state data (incidence) onto the counties 
  - Plot using ggmap 
  - Work into animate 
  
  
  
